/* =========================================================
   BHUKKADJIV
   SMOOTH & OPTIMIZED JAVASCRIPT
========================================================= */


/* =========================================================
   CONFIG
========================================================= */

const CONTACT = {
    wa: "918010679493",
    email: "atharvp0618@gmail.com",
    pin: "1234"
};


/* =========================================================
   WEB3FORMS CONFIG
========================================================= */

/*
    Replace this with the Access Key generated by Web3Forms.

    The Access Key should be connected to the client's
    receiving Gmail address.
*/

const WEB3FORMS_ACCESS_KEY =
    "2a2b0d1d-fb7d-439d-946e-087301f67b2f";

const WEB3FORMS_ENDPOINT =
    "https://api.web3forms.com/submit";

/* =========================================================
   HELPERS
========================================================= */

const $ = id => document.getElementById(id);

const qs = selector =>
    document.querySelector(selector);

const qsa = selector =>
    [...document.querySelectorAll(selector)];


/* =========================================================
   APP STATE
========================================================= */

const state = {
    language: false,
    diaryFilter: "All",
    trailFilter: "All",
    diaryUnlocked: false,
    diaryPosts: []
};


/* =========================================================
   SAFE LOCAL STORAGE
========================================================= */

const storage = {

    get(key, fallback = null) {

        try {

            const value =
                localStorage.getItem(key);

            return value ?? fallback;

        } catch (error) {

            console.warn(
                `Unable to read localStorage: ${key}`,
                error
            );

            return fallback;
        }
    },


    set(key, value) {

        try {

            localStorage.setItem(
                key,
                value
            );

            return true;

        } catch (error) {

            console.warn(
                `Unable to save localStorage: ${key}`,
                error
            );

            return false;
        }
    }

};


/* =========================================================
   NAVIGATION
========================================================= */

function getNavigationTarget(href) {

    if (!href || !href.startsWith("#")) {
        return null;
    }


    /* Collaboration */

    if (href === "#collab") {

        return (
            $("collab") ||
            $("enquire")
        );
    }


    /* Trail */

    if (href === "#trail") {

        const trail =
            $("trail");

        if (trail) {
            return trail;
        }


        const trailPosts =
            $("tposts");

        const trailFilters =
            $("tfilters");


        if (trailPosts) {

            return (
                trailPosts.closest("section") ||
                trailPosts
            );
        }


        if (trailFilters) {

            return (
                trailFilters.closest("section") ||
                trailFilters
            );
        }


        return null;
    }


    /* Normal section */

    try {

        return document.querySelector(href);

    } catch {

        return null;
    }
}


/* =========================================================
   SMOOTH SCROLL
========================================================= */

function smoothScrollTo(target) {

    if (!target) {
        return;
    }


    const nav =
        qs("nav");


    const navHeight =
        nav
            ? nav.getBoundingClientRect().height
            : 0;


    const offset = 15;


    const position =
        target.getBoundingClientRect().top +
        window.scrollY -
        navHeight -
        offset;


    window.scrollTo({

        top: Math.max(0, position),

        behavior: "smooth"

    });
}


/* =========================================================
   NAVIGATION EVENTS
========================================================= */

function setupNavigation() {

    qsa('a[href^="#"]').forEach(link => {

        link.addEventListener(
            "click",
            event => {

                const href =
                    link.getAttribute("href");


                if (
                    !href ||
                    href === "#"
                ) {
                    return;
                }


                const target =
                    getNavigationTarget(href);


                if (!target) {
                    return;
                }


                event.preventDefault();


                smoothScrollTo(target);


                /*
                    Update URL without triggering
                    browser's default jump.
                */

                try {

                    history.pushState(
                        null,
                        "",
                        href
                    );

                } catch {}


                closeMobileMenu();

            }
        );

    });

}


/* =========================================================
   INITIAL HASH
========================================================= */

function handleInitialHash() {

    const hash =
        window.location.hash;


    if (!hash) {
        return;
    }


    setTimeout(() => {

        const target =
            getNavigationTarget(hash);


        if (target) {
            smoothScrollTo(target);
        }

    }, 250);

}


/* =========================================================
   MOBILE NAVIGATION
========================================================= */

function setupMobileMenu() {

    const nav =
        qs("nav");


    if (!nav) {
        return;
    }


    let menuButton =
        $("mobileMenu");


    /*
        Create mobile menu button
        automatically.
    */

    if (!menuButton) {

        menuButton =
            document.createElement("button");


        menuButton.id =
            "mobileMenu";


        menuButton.type =
            "button";


        menuButton.className =
            "mobile-menu-btn";


        menuButton.setAttribute(
            "aria-label",
            "Open navigation menu"
        );


        menuButton.setAttribute(
            "aria-expanded",
            "false"
        );


        menuButton.innerHTML =
            "☰";


        const tools =
            nav.querySelector(".tools");


        if (tools) {

            nav.insertBefore(
                menuButton,
                tools
            );

        } else {

            nav.appendChild(
                menuButton
            );
        }

    }


    menuButton.addEventListener(
        "click",
        event => {

            event.stopPropagation();

            const isOpen =
                nav.classList.toggle(
                    "mobile-open"
                );


            menuButton.innerHTML =
                isOpen
                    ? "✕"
                    : "☰";


            menuButton.setAttribute(
                "aria-expanded",
                String(isOpen)
            );

        }
    );


    document.addEventListener(
        "click",
        event => {

            if (
                !nav.contains(event.target)
            ) {

                closeMobileMenu();

            }

        }
    );

}


function closeMobileMenu() {

    const nav =
        qs("nav");


    const button =
        $("mobileMenu");


    if (!nav) {
        return;
    }


    nav.classList.remove(
        "mobile-open"
    );


    if (button) {

        button.innerHTML =
            "☰";


        button.setAttribute(
            "aria-expanded",
            "false"
        );

    }

}


/* =========================================================
   THEME
========================================================= */

function setTheme(isDark) {

    document.documentElement.dataset.theme =
        isDark
            ? "dark"
            : "";


    const themeButton =
        $("theme");


    if (themeButton) {

        themeButton.textContent =
            isDark
                ? "☀️"
                : "🌙";

    }


    storage.set(
        "bj_dark",
        isDark ? "1" : ""
    );

}


function setupTheme() {

    const button =
        $("theme");


    if (!button) {
        return;
    }


    const saved =
        storage.get(
            "bj_dark",
            ""
        );


    if (saved) {
        setTheme(true);
    }


    button.addEventListener(
        "click",
        () => {

            const isDark =
                document.documentElement
                    .dataset
                    .theme === "dark";


            setTheme(!isDark);

        }
    );

}


/* =========================================================
   LANGUAGE
========================================================= */

/*
    Keep your existing large MR object
    and PH object here.
*/


const orig =
    new WeakMap();


function applyLanguage() {

    const isMarathi =
        state.language;


    /*
        Translate regular text nodes.
    */

    const walker =
        document.createTreeWalker(
            document.body,
            NodeFilter.SHOW_TEXT,
            {
                acceptNode(node) {

                    const parent =
                        node.parentNode;


                    if (
                        parent &&
                        parent.closest(
                            "script,style"
                        )
                    ) {

                        return NodeFilter.FILTER_REJECT;
                    }


                    return NodeFilter.FILTER_ACCEPT;
                }
            }
        );


    const nodes = [];


    while (walker.nextNode()) {

        nodes.push(
            walker.currentNode
        );

    }


    nodes.forEach(node => {

        const originalText =
            node.nodeValue.trim();


        if (isMarathi) {

            if (
                typeof MR !== "undefined" &&
                MR[originalText]
            ) {

                if (
                    !orig.has(node)
                ) {

                    orig.set(
                        node,
                        node.nodeValue
                    );

                }


                node.nodeValue =
                    MR[originalText];

            }

        } else {

            if (orig.has(node)) {

                node.nodeValue =
                    orig.get(node);


                orig.delete(node);

            }

        }

    });


    /*
        data-mr elements.
    */

    qsa("[data-mr]").forEach(
        element => {

            if (!element.dataset.en) {

                element.dataset.en =
                    element.innerHTML;

            }


            element.innerHTML =
                isMarathi
                    ? element.dataset.mr
                    : element.dataset.en;

        }
    );


    /*
        Placeholders.
    */

    qsa("[placeholder]").forEach(
        element => {

            if (!element.dataset.ph) {

                element.dataset.ph =
                    element.placeholder;

            }


            if (
                isMarathi &&
                typeof PH !== "undefined" &&
                PH[element.dataset.ph]
            ) {

                element.placeholder =
                    PH[element.dataset.ph];

            } else {

                element.placeholder =
                    element.dataset.ph;

            }

        }
    );


    document.documentElement.lang =
        isMarathi
            ? "mr"
            : "en";


    const languageButton =
        $("lang");


    if (languageButton) {

        languageButton.textContent =
            isMarathi
                ? "EN"
                : "मराठी";

    }

}


function setupLanguage() {

    /*
        Store option values.
    */

    qsa("option").forEach(
        option => {

            option.value =
                option.textContent;

        }
    );


    const button =
        $("lang");


    if (!button) {
        return;
    }


    const saved =
        storage.get(
            "bj_mr",
            ""
        );


    if (saved) {

        state.language =
            true;

        applyLanguage();

    }


    button.addEventListener(
        "click",
        () => {

            state.language =
                !state.language;


            storage.set(
                "bj_mr",
                state.language
                    ? "1"
                    : ""
            );


            applyLanguage();

        }
    );

}


/* =========================================================
   DIARY DATA
========================================================= */

const BASE = [

    [
        "30 Sep",
        "Routine",
        "Clinic, chai, then gym",
        "Sample post: patients in the morning, a chai break I can't skip and a leg day I wasn't ready for.",
        "6:30 AM – 9 PM"
    ],

    [
        "29 Sep",
        "Food",
        "The thali that made me quiet",
        "Sample post: where I ate, what I ordered and the one thing you must not skip.",
        "1 PM"
    ],

    [
        "28 Sep",
        "Style",
        "Gold, green saree and festive mood",
        "Sample post: how I styled a traditional set for the season.",
        "5 PM"
    ]

];


/* =========================================================
   LOAD DIARY POSTS
========================================================= */

function loadDiaryPosts() {

    try {

        const saved =
            storage.get(
                "bj_posts",
                "[]"
            );


        const parsed =
            JSON.parse(saved);


        state.diaryPosts =
            Array.isArray(parsed)
                ? parsed
                : [];

    } catch {

        state.diaryPosts = [];

    }

}


/* =========================================================
   SAVE DIARY POSTS
========================================================= */

function saveDiaryPosts() {

    storage.set(
        "bj_posts",
        JSON.stringify(
            state.diaryPosts
        )
    );

}


/* =========================================================
   DIARY FILTERS
========================================================= */

function getDiaryPosts() {

    return [

        ...state.diaryPosts.map(
            (post, index) => [
                ...post,
                index
            ]
        ),

        ...BASE

    ];

}


/* =========================================================
   DRAW DIARY FILTERS
========================================================= */

function drawDiaryFilters(posts) {

    const filters =
        $("filters");


    if (!filters) {
        return;
    }


    const categories = [

        "All",

        ...new Set(
            posts.map(
                post => post[1]
            )
        )

    ];


    filters.innerHTML = "";


    categories.forEach(
        category => {

            const button =
                document.createElement("button");


            button.type =
                "button";


            button.textContent =
                category;


            button.classList.toggle(
                "on",
                category ===
                state.diaryFilter
            );


            button.addEventListener(
                "click",
                () => {

                    state.diaryFilter =
                        category;


                    drawDiary();

                }
            );


            filters.appendChild(
                button
            );

        }
    );

}


/* =========================================================
   DRAW DIARY POSTS
========================================================= */

function drawDiaryPosts(posts) {

    const container =
        $("posts");


    if (!container) {
        return;
    }


    container.innerHTML = "";


    posts
        .filter(post =>
            state.diaryFilter === "All" ||
            post[1] === state.diaryFilter
        )
        .forEach(post => {

            const article =
                document.createElement(
                    "article"
                );


            article.className =
                "post";


            /*
                Delete button for
                user-created posts.
            */

            if (
                post[5] !== undefined
            ) {

                const deleteButton =
                    document.createElement(
                        "button"
                    );


                deleteButton.type =
                    "button";


                deleteButton.className =
                    "del";


                deleteButton.title =
                    "Delete";


                deleteButton.textContent =
                    "✕";


                deleteButton.addEventListener(
                    "click",
                    () => {

                        deleteDiaryPost(
                            post[5]
                        );

                    }
                );


                article.appendChild(
                    deleteButton
                );

            }


            const tag =
                document.createElement(
                    "span"
                );


            tag.className =
                "tag";


            tag.textContent =
                post[1];


            const title =
                document.createElement(
                    "h3"
                );


            title.textContent =
                post[2];


            const description =
                document.createElement(
                    "p"
                );


            description.textContent =
                post[3];


            const when =
                document.createElement(
                    "div"
                );


            when.className =
                "when";


            when.textContent =
                post[0] +
                (
                    post[4]
                        ? " · " + post[4]
                        : ""
                );


            article.appendChild(tag);

            article.appendChild(title);

            article.appendChild(description);

            article.appendChild(when);


            container.appendChild(
                article
            );

        });

}


/* =========================================================
   DRAW DIARY
========================================================= */

function drawDiary() {

    const posts =
        getDiaryPosts();


    drawDiaryFilters(posts);

    drawDiaryPosts(posts);


    if (state.language) {
        applyLanguage();
    }

}


/* =========================================================
   DELETE DIARY POST
========================================================= */

function deleteDiaryPost(index) {

    if (
        index < 0 ||
        index >= state.diaryPosts.length
    ) {
        return;
    }


    state.diaryPosts.splice(
        index,
        1
    );


    saveDiaryPosts();

    drawDiary();

}


/* =========================================================
   DIARY WRITE PANEL
========================================================= */

function setupDiaryEditor() {

    const writeButton =
        $("wbtn");


    const panel =
        $("wpanel");


    if (!writeButton || !panel) {
        return;
    }


    writeButton.addEventListener(
        "click",
        () => {

            if (
                !state.diaryUnlocked
            ) {

                const enteredPin =
                    window.prompt(
                        "Enter PIN"
                    );


                if (
                    enteredPin !==
                    CONTACT.pin
                ) {

                    return;

                }


                state.diaryUnlocked =
                    true;

            }


            panel.classList.toggle(
                "open"
            );

        }
    );

}


/* =========================================================
   SAVE NEW DIARY POST
========================================================= */

function setupDiarySave() {

    const button =
        $("psave");


    if (!button) {
        return;
    }


    button.addEventListener(
        "click",
        () => {

            const title =
                $("pt")
                    ?.value
                    .trim();


            const text =
                $("px")
                    ?.value
                    .trim();


            if (!title || !text) {

                alert(
                    "Please enter a title and post content."
                );

                return;

            }


            const category =
                $("pc")
                    ?.value ||
                "Routine";


            const place =
                $("pm")
                    ?.value
                    .trim() ||
                "";


            const date =
                new Date()
                    .toLocaleDateString(
                        "en-GB",
                        {
                            day: "numeric",
                            month: "short"
                        }
                    );


            state.diaryPosts.unshift([

                date,

                category,

                title,

                text,

                place

            ]);


            saveDiaryPosts();


            /*
                Clear fields.
            */

            if ($("pt")) {
                $("pt").value = "";
            }


            if ($("px")) {
                $("px").value = "";
            }


            if ($("pm")) {
                $("pm").value = "";
            }


            state.diaryFilter =
                "All";


            drawDiary();

        }
    );

}


/* =========================================================
   TRAIL DATA
========================================================= */

const TRAIL = [

    [
        "Sample Thali House",
        "Kolhapur",
        "Thali",
        5,
        "Sample note: full meal, zero regrets."
    ],

    [
        "Sample Misal Corner",
        "Kolhapur",
        "Snacks",
        4,
        "Sample note: spicy, so ask for extra pav."
    ],

    [
        "Sample Juice Bar",
        "Pune",
        "Drinks",
        4,
        "Sample note: fresh and not too sweet."
    ],

    [
        "Sample Sweet Shop",
        "Kolhapur",
        "Sweets",
        5,
        "Sample note: come early, it sells out."
    ]

];


/* =========================================================
   TRAIL FILTERS
========================================================= */

function drawTrailFilters() {

    const container =
        $("tfilters");


    if (!container) {
        return;
    }


    const categories = [

        "All",

        ...new Set(
            TRAIL.map(
                place => place[2]
            )
        )

    ];


    container.innerHTML = "";


    categories.forEach(
        category => {

            const button =
                document.createElement(
                    "button"
                );


            button.type =
                "button";


            button.textContent =
                category;


            button.classList.toggle(
                "on",
                category ===
                state.trailFilter
            );


            button.addEventListener(
                "click",
                () => {

                    state.trailFilter =
                        category;


                    drawTrail();

                }
            );


            container.appendChild(
                button
            );

        }
    );

}


/* =========================================================
   TRAIL POSTS
========================================================= */

function drawTrailPosts() {

    const container =
        $("tposts");


    if (!container) {
        return;
    }


    container.innerHTML = "";


    TRAIL
        .filter(place =>
            state.trailFilter === "All" ||
            place[2] ===
            state.trailFilter
        )
        .forEach(place => {

            const article =
                document.createElement(
                    "article"
                );


            article.className =
                "post";


            const tag =
                document.createElement(
                    "span"
                );


            tag.className =
                "tag";


            tag.textContent =
                `${place[2]} · ${place[1]}`;


            const title =
                document.createElement(
                    "h3"
                );


            title.textContent =
                place[0];


            const stars =
                document.createElement(
                    "div"
                );


            stars.className =
                "stars";


            stars.textContent =
                "★".repeat(place[3]) +
                "☆".repeat(
                    5 - place[3]
                );


            const note =
                document.createElement(
                    "p"
                );


            note.textContent =
                place[4];


            article.appendChild(tag);

            article.appendChild(title);

            article.appendChild(stars);

            article.appendChild(note);


            container.appendChild(
                article
            );

        });

}


/* =========================================================
   DRAW TRAIL
========================================================= */

function drawTrail() {

    drawTrailFilters();

    drawTrailPosts();


    if (state.language) {
        applyLanguage();
    }

}


/* =========================================================
   FOOD RANDOMIZER
========================================================= */

const FOODS = [

    "Misal pav 🌶️",

    "Kolhapuri thali 🍛",

    "Vada pav",

    "Puran poli 🍯",

    "Pav bhaji",

    "Sabudana khichdi",

    "Tambda rassa 🔥",

    "Modak 🪔",

    "Poha & chai ☕",

    "Bhakri & thecha"

];


function setupFoodRandomizer() {

    const button =
        $("pick");


    const dish =
        $("dish");


    if (!button || !dish) {
        return;
    }


    let timer = null;


    button.addEventListener(
        "click",
        () => {

            clearInterval(timer);


            let count = 0;


            timer =
                setInterval(
                    () => {

                        dish.textContent =
                            FOODS[
                                Math.floor(
                                    Math.random() *
                                    FOODS.length
                                )
                            ];


                        count++;


                        if (
                            count >= 12
                        ) {

                            clearInterval(
                                timer
                            );

                        }

                    },
                    90
                );

        }
    );

}

/* =========================================================
   COLLABORATION MESSAGE
========================================================= */

function getCollaborationMessage() {

    const brand =
        $("eb")
            ?.value
            .trim() ||
        "[brand]";


    const visitorEmail =
        $("ee")
            ?.value
            .trim() ||
        "";


    const category =
        $("ec")
            ?.value ||
        "";


    const requirement =
        $("ef")
            ?.value ||
        "";


    const timeline =
        $("ed")
            ?.value
            .trim() ||
        "flexible";


    const idea =
        $("ei")
            ?.value
            .trim() ||
        "";


    return `Hi Dr. Prajakta! 👋

We’re from ${brand}, and we’d love to collaborate with you for ${requirement}.

${idea}

We’re looking at ${timeline}.

You can reach us at ${visitorEmail}.

Hope to hear from you soon 😊`;

}

/* =========================================================
   WHATSAPP
========================================================= */

function setupWhatsApp() {

    const button =
        $("ewa");


    if (!button) {
        return;
    }


    button.addEventListener(
        "click",
        () => {

            const message =
                getCollaborationMessage();


            const url =
                "https://wa.me/" +
                CONTACT.wa +
                "?text=" +
                encodeURIComponent(
                    message
                );


            window.open(
                url,
                "_blank",
                "noopener,noreferrer"
            );

        }
    );

}

/* =========================================================
   EMAIL — WEB3FORMS
========================================================= */

function setupEmail() {

    const button =
        $("email");


    if (!button) {
        return;
    }


    button.addEventListener(
        "click",
        async () => {

            /* =================================================
               GET FORM VALUES
            ================================================= */

            const brand =
                $("eb")
                    ?.value
                    .trim() ||
                "";


            const visitorEmail =
                $("ee")
                    ?.value
                    .trim() ||
                "";


            const category =
                $("ec")
                    ?.value ||
                "";


            const requirement =
                $("ef")
                    ?.value ||
                "";


            const timeline =
                $("ed")
                    ?.value
                    .trim() ||
                "";


            const idea =
                $("ei")
                    ?.value
                    .trim() ||
                "";


            const status =
                $("estat");


            /* =================================================
               VALIDATION
            ================================================= */

            if (!brand) {

                if (status) {

                    status.textContent =
                        "Please enter your brand / business name.";

                    status.style.color =
                        "#d64545";

                }

                $("eb")?.focus();

                return;
            }


            if (!visitorEmail) {

                if (status) {

                    status.textContent =
                        "Please enter your email address.";

                    status.style.color =
                        "#d64545";

                }

                $("ee")?.focus();

                return;
            }


            if (
                !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(
                    visitorEmail
                )
            ) {

                if (status) {

                    status.textContent =
                        "Please enter a valid email address.";

                    status.style.color =
                        "#d64545";

                }

                $("ee")?.focus();

                return;
            }


            if (!idea) {

                if (status) {

                    status.textContent =
                        "Please tell us about your collaboration idea.";

                    status.style.color =
                        "#d64545";

                }

                $("ei")?.focus();

                return;
            }


            /* =================================================
               CHECK WEB3FORMS KEY
            ================================================= */

            if (
                !WEB3FORMS_ACCESS_KEY ||
                WEB3FORMS_ACCESS_KEY ===
                "YOUR_WEB3FORMS_ACCESS_KEY"
            ) {

                if (status) {

                    status.textContent =
                        "Web3Forms Access Key is not configured yet.";

                    status.style.color =
                        "#d64545";

                }

                return;
            }


            /* =================================================
               BUTTON LOADING STATE
            ================================================= */

            const originalText =
                button.textContent;


            button.disabled = true;

            button.style.opacity =
                "0.7";

            button.style.cursor =
                "wait";

            button.textContent =
                "Sending...";


            if (status) {

                status.textContent =
                    "Sending your enquiry...";

                status.style.color =
                    "var(--leaf)";

            }


            /* =================================================
               CREATE FORM DATA
            ================================================= */

            const formData =
                new FormData();


            formData.append(
                "access_key",
                WEB3FORMS_ACCESS_KEY
            );


            formData.append(
                "name",
                brand
            );


            formData.append(
                "email",
                visitorEmail
            );


            formData.append(
                "subject",
                `New Collaboration Enquiry - ${brand}`
            );


            formData.append(
                "Brand / Business",
                brand
            );


            formData.append(
                "Category",
                category
            );


            formData.append(
                "What do you need?",
                requirement
            );


            formData.append(
                "Preferred Timeline",
                timeline ||
                "Not specified"
            );


            formData.append(
                "Collaboration Idea",
                idea
            );


            /* =================================================
               SEND TO WEB3FORMS
            ================================================= */

            try {

                const response =
                    await fetch(
                        WEB3FORMS_ENDPOINT,
                        {
                            method: "POST",

                            body: formData,

                            headers: {
                                "Accept":
                                    "application/json"
                            }
                        }
                    );


                const result =
                    await response.json();


                /* =================================================
                   SUCCESS
                ================================================= */

                if (
                    response.ok &&
                    result.success
                ) {

                    if (status) {

                        status.textContent =
                            "Message sent successfully! We'll get back to you soon.";

                        status.style.color =
                            "var(--leaf)";

                    }


                    /* Clear form */

                    if ($("eb")) {
                        $("eb").value = "";
                    }


                    if ($("ee")) {
                        $("ee").value = "";
                    }


                    if ($("ec")) {
                        $("ec").selectedIndex = 0;
                    }


                    if ($("ef")) {
                        $("ef").selectedIndex = 0;
                    }


                    if ($("ed")) {
                        $("ed").value = "";
                    }


                    if ($("ei")) {
                        $("ei").value = "";
                    }


                } else {

                    throw new Error(
                        result.message ||
                        "Web3Forms submission failed."
                    );

                }


            } catch (error) {

                console.error(
                    "Web3Forms error:",
                    error
                );


                if (status) {

                    status.textContent =
                        "Unable to send the message. Please try again.";

                    status.style.color =
                        "#d64545";

                }


            } finally {

                /* Restore button */

                button.disabled =
                    false;

                button.style.opacity =
                    "";

                button.style.cursor =
                    "";

                button.textContent =
                    originalText;

            }

        }
    );

}


/* =========================================================
   COPY INSTAGRAM MESSAGE
========================================================= */

function setupCopyMessage() {

    const button =
        $("ecopy");


    if (!button) {
        return;
    }


    button.addEventListener(
        "click",
        async () => {

            const message =
                getCollaborationMessage();


            try {

                await navigator.clipboard.writeText(
                    message
                );


                if ($("estat")) {

                    $("estat").textContent =
                        "Copied! Now paste it in Instagram DM.";

                    $("estat").style.color =
                        "var(--leaf)";

                }


            } catch {

                const textarea =
                    document.createElement(
                        "textarea"
                    );


                textarea.value =
                    message;


                textarea.style.position =
                    "fixed";


                textarea.style.opacity =
                    "0";


                document.body.appendChild(
                    textarea
                );


                textarea.select();


                try {

                    document.execCommand(
                        "copy"
                    );


                    if ($("estat")) {

                        $("estat").textContent =
                            "Copied! Now paste it in Instagram DM.";

                        $("estat").style.color =
                            "var(--leaf)";

                    }


                } catch {

                    if ($("estat")) {

                        $("estat").textContent =
                            "Copy failed, please select the text manually.";

                        $("estat").style.color =
                            "#d64545";

                    }

                }


                textarea.remove();

            }

        }
    );

}

/* =========================================================
   SCROLL REVEAL
========================================================= */

function setupRevealAnimations() {

    const elements =
        qsa(
            ".rv,.tile,.fact"
        );


    if (!elements.length) {
        return;
    }


    /*
        Respect reduced-motion preference.
    */

    const reducedMotion =
        window.matchMedia(
            "(prefers-reduced-motion: reduce)"
        ).matches;


    if (reducedMotion) {

        elements.forEach(
            element =>
                element.classList.add("in")
        );


        return;
    }


    /*
        Add initial class.
    */

    elements.forEach(
        element => {

            element.classList.add(
                "rv"
            );

        }
    );


    if (
        !("IntersectionObserver" in window)
    ) {

        elements.forEach(
            element =>
                element.classList.add("in")
        );


        return;
    }


    const observer =
        new IntersectionObserver(
            entries => {

                entries.forEach(
                    entry => {

                        if (
                            !entry.isIntersecting
                        ) {
                            return;
                        }


                        entry.target.classList.add(
                            "in"
                        );


                        observer.unobserve(
                            entry.target
                        );

                    }
                );

            },
            {
                threshold: 0.12,

                rootMargin:
                    "0px 0px -40px 0px"
            }
        );


    elements.forEach(
        element =>
            observer.observe(element)
    );

}


/* =========================================================
   KEYBOARD ESCAPE
========================================================= */

function setupKeyboardControls() {

    document.addEventListener(
        "keydown",
        event => {

            if (
                event.key === "Escape"
            ) {

                closeMobileMenu();

            }

        }
    );

}


/* =========================================================
   INITIALIZE APPLICATION
========================================================= */

function initApp() {

    /*
        Load saved data.
    */

    loadDiaryPosts();


    /*
        Setup all modules.
    */

    setupNavigation();

    setupMobileMenu();

    setupTheme();

    setupLanguage();

    setupDiaryEditor();

    setupDiarySave();

    setupFoodRandomizer();

    setupWhatsApp();

    setupEmail();

    setupCopyMessage();

    setupRevealAnimations();

    setupKeyboardControls();


    /*
        Render dynamic sections.
    */

    drawDiary();

    drawTrail();


    /*
        Handle URL hash after
        everything has rendered.
    */

    handleInitialHash();

}


/* =========================================================
   START
========================================================= */

if (
    document.readyState ===
    "loading"
) {

    document.addEventListener(
        "DOMContentLoaded",
        initApp
    );

} else {

    initApp();

}

/* =========================================================
   MOBILE NAVIGATION
========================================================= */

document.addEventListener("DOMContentLoaded", () => {

    const nav = document.getElementById("mainNav");
    const menuBtn = document.getElementById("mobileMenuBtn");
    const navLinks = document.querySelectorAll("#navLinks a");

    if (!nav || !menuBtn) {
        return;
    }


    /* Open / close menu */

    menuBtn.addEventListener("click", () => {

        const isOpen = nav.classList.toggle("menu-open");

        menuBtn.setAttribute(
            "aria-expanded",
            String(isOpen)
        );

        menuBtn.setAttribute(
            "aria-label",
            isOpen
                ? "Close navigation menu"
                : "Open navigation menu"
        );

        menuBtn.textContent = isOpen
            ? "✕"
            : "☰";
    });


    /* Close menu after clicking a link */

    navLinks.forEach((link) => {

        link.addEventListener("click", () => {

            nav.classList.remove("menu-open");

            menuBtn.setAttribute(
                "aria-expanded",
                "false"
            );

            menuBtn.setAttribute(
                "aria-label",
                "Open navigation menu"
            );

            menuBtn.textContent = "☰";
        });

    });


    /* Close menu when resizing to desktop */

    window.addEventListener("resize", () => {

        if (window.innerWidth > 900) {

            nav.classList.remove("menu-open");

            menuBtn.setAttribute(
                "aria-expanded",
                "false"
            );

            menuBtn.setAttribute(
                "aria-label",
                "Open navigation menu"
            );

            menuBtn.textContent = "☰";
        }

    });

});